name: animadate
services:
  app:
    image: DOCKER_DEPLOY_APP_IMAGE
    container_name: animadate_app
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3000:3000
  cron:
    image: DOCKER_DEPLOY_CRONS_IMAGE
    container_name: animadate_crons
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
  doc:
    image: DOCKER_DEPLOY_DOCS_IMAGE
    container_name: animadate_doc
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3001:3000
    volumes:
      - .:/docs/.docusaurus
  landing:
    image: DOCKER_DEPLOY_LANDING_IMAGE
    container_name: animadate_landing
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3002:3000
  db:
    image: postgis/postgis:latest
    container_name: animadate_db
    restart: unless-stopped
    volumes:
      - animadate-postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_ADDITIONAL_MULTIPLE_DATABASES: events
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: animadate_redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - animadate-redis-data:/data
    ports:
      - 6379:6379
volumes:
  animadate-postgres-data:
  animadate-redis-data:
