name: animadate
services:
  db:
    image: postgis/postgis:latest
    container_name: animadate_db
    restart: unless-stopped
    volumes:
      - animadate-postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_ADDITIONAL_MULTIPLE_DATABASES: events
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: animadate_redis
    command: /bin/sh -c "redis-server"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - animadate-redis-data:/data
    ports:
      - 6379:6379
volumes:
  animadate-postgres-data:
  animadate-redis-data:
