/*
  Warnings:

  - The values [INTELLIGENT,LOVING,GENTLE,CHEERFUL] on the enum `CHARACTERISTIC` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "CHARACTERISTIC_new" AS ENUM ('FRIENDLY', 'PLAYFUL', 'CALM', 'PROTECTIVE', 'AFFECTIONATE', 'CURIOUS', 'ENERGETIC', 'SWEET', 'HAPPY', 'QUIET', 'SHY', 'SOCIAL', 'BRAVE', 'CLEVER', 'COOL', 'CRAZY', 'CUTE', 'DOCILE', 'DYNAMIC', 'EASYGOING', 'ENTHUSIASTIC', 'FEARLESS', 'FUNNY', 'JOYFUL', 'KIND', 'MATURE', 'OBEDIENT', 'PATIENT', 'PEACEFUL', 'SENSITIVE', 'SERIOUS', 'SMART', 'STRONG', 'TENDER', 'TOUGH', 'TRUSTWORTHY', 'WISE', 'ZEALOUS', 'ADAPTABLE', 'AMUSING', 'CHARMING', 'COURAGEOUS', 'DETERMINED', 'FLEXIBLE');
ALTER TABLE "Characteristic" ALTER COLUMN "value" TYPE "CHARACTERISTIC_new" USING ("value"::text::"CHARACTERISTIC_new");
ALTER TABLE "Pet" ALTER COLUMN "researchedCharacteristics" TYPE "CHARACTERISTIC_new"[] USING ("researchedCharacteristics"::text::"CHARACTERISTIC_new"[]);
ALTER TYPE "CHARACTERISTIC" RENAME TO "CHARACTERISTIC_old";
ALTER TYPE "CHARACTERISTIC_new" RENAME TO "CHARACTERISTIC";
DROP TYPE "CHARACTERISTIC_old";
COMMIT;
